<a href="https://colab.research.google.com/github/ummuhankeles/machine-learning/blob/main/week2_first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [2]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [3]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [4]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [5]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[54 62 51 83 74 58]


In [6]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.30896546 0.87768832 0.89592545 0.86424284 0.54591287 0.39061427]


In [7]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.30896546 2.87768832 2.89592545 2.86424284 2.54591287 2.39061427]


In [8]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[162 186 153 249 222 174]


**Task 1 : Create a Linear Dataset**


In [9]:
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


**Task 2 : Add Some Noise to the Dataset**

In [10]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[ 0.81456209 -1.62987648  1.59470987 -0.55394141 -1.52788    -1.90100843
 -1.18152641  1.64860332  0.37051156  1.20078883 -0.5162239  -1.93796536
  0.28104781 -1.41496983 -1.18180205]
[22.81456209 23.37012352 29.59470987 30.44605859 32.47212    35.09899157
 38.81847359 44.64860332 46.37051156 50.20078883 51.4837761  53.06203464
 58.28104781 59.58503017 62.81819795]
